Type: OdLidarPostProcessSany
Config:
  Tracker:
    Switch: true
    TrackerPipelineMethod: SimpleTrack
    TrackerPipelineParams:
      min_lifetime_output: 3
      max_consecutive_lost_num: 5
      min_consecutive_valid_num: 3
      origin_xy_offset: [16.0, 2.0] # [x方向的矢量偏移量，y方向的绝对值偏移量]
      IDPool:
        start_id: 1
        max_id: 255
      MatcherMethod: OneStageMatcher
      MatcherParams:
        MatcherOptions:
          cost_thresh: 0.99
          bound_value: 1.00
        method: NORMAL_DISTANCE # NORMAL_DISTANCE、FUSION_DISTANCE
        max_distance: 5.0 # 前后帧最大距离(m)
        max_velocity: 50 # 障碍物最大速度(m/s)
        max_theta_diff: 0.785 # pi/4, heading角度差阈值(rad)
        max_projection_distance: 2.0 # 在heading垂直方向上的投影距离阈值(m)
      TrackerMethod: TailCenterTrackerCV # NearestCornerTrackerCV、TailCenterTrackerCV
      TrackerParams:
        fov_angle: 120.0
        x_offset: 7.5
        y_offset: 1.6
  ClusterDetection:
    Switch: true
    Params:
      ClusterMethod: BEVCCL
      ClusterParams:
        map_range_min_x: 0.0
        map_range_max_x: 85.0
        map_range_min_y: -30.0
        map_range_max_y: 30.0
        map_range_min_z: -2.0
        map_range_max_z: 3.0
        map_resolution_x: 0.5
        map_resolution_y: 0.3
        min_points_num: 10
      FilterByRules:
        HeightFilter:
          Switch: true
          range_x_threshold: 20.0
          height_threshold: 1.2
        IntensityFilter:
          Switch: true
          low_intensity_threshold: 8.5
          high_intensity_threshold: 12.5
          high_count_threshold: 4
          ratio_threshold: 0.4
      MergeObjects:
        dilate_x: 4.0
        dilate_y: 0.6
        overlap_thresh: 0.1
