Type: OdLidarPostProcessSany
Config:
  Tracker:
    Switch: true
    TrackerPipelineMethod: SimpleTrack
    TrackerPipelineParams:
      GeneralParams:
        min_lifetime_output: 3
        max_consecutive_lost_num: 5
        min_consecutive_valid_num: 3
        origin_xy_offset: [16.0, 2.0] # [x方向的矢量偏移量，y方向的绝对值偏移量] 参数可省略
        nms_by_polygon: false # nms中使用polygon(默认bbox)进行重叠率 参数可省略
        predict_by_velocity: true # 轨迹未匹配成功时是否要根据速度进行预测(默认要预测) 参数可省略
      IDPool:
        start_id: 1
        max_id: 255
      MatcherMethod: OneStageMatcher
      MatcherParams:
        MatcherOptions:
          cost_thresh: 0.99
          bound_value: 1.00
        DistanceMeasurementMethod: TailCenterDistance
        DistanceMeasurementParams:
          max_distance: 5.0 # 前后帧最大距离(m)
          max_velocity: 50 # 障碍物最大速度(m/s)
          max_theta_diff: 0.785 # pi/4, heading角度差阈值(rad)
          max_projection_distance: 2.0 # 在heading垂直方向上的投影距离阈值(m)
      TrackerMethod: TailCenterTrackerCV # NearestCornerTrackerCV、TailCenterTrackerCV
      TrackerParams:
        fov_angle: 120.0
        x_offset: 7.5
        y_offset: 1.6
  ClusterDetection:
    Switch: true
    Params:
      RemoveObjectPoints:
        Switch: true
        Params:
          scale: 5.0
          x_range: 200.0
          y_range: 200.0
          x_offset: 0.0
          y_offset: 100.0
          x_dilate: 0.5
          y_dilate: 0.5
      ClusterMethod: BEVCCL
      ClusterParams:
        map_range_min_x: 0.0
        map_range_max_x: 85.0
        map_range_min_y: -30.0
        map_range_max_y: 30.0
        map_range_min_z: -2.0
        map_range_max_z: 3.0
        map_resolution_x: 0.5
        map_resolution_y: 0.3
        min_points_num: 10
      FilterByRules:
        HeightFilter:
          Switch: true
          range_x_threshold: 20.0
          height_threshold: 1.2
        IntensityFilter:
          Switch: true
          low_intensity_threshold: 8.5
          high_intensity_threshold: 12.5
          high_count_threshold: 4
          ratio_threshold: 0.4
      MergeObjects:
        dilate_x: 4.0
        dilate_y: 0.6
        overlap_thresh: 0.1
      Tracker:
        Switch: true
        TrackerPipelineMethod: SimpleTrack
        TrackerPipelineParams:
          GeneralParams:
            min_lifetime_output: 0
            max_consecutive_lost_num: 5
            min_consecutive_valid_num: 3
            origin_xy_offset: [16.0, 2.0] # [x方向的矢量偏移量，y方向的绝对值偏移量] 参数可省略
            nms_by_polygon: true # nms中使用polygon(默认bbox)进行重叠率 参数可省略
            predict_by_velocity: false # 轨迹未匹配成功时是否要根据速度进行预测(默认要预测) 参数可省略
          MatcherMethod: OneStageMatcher
          MatcherParams:
            MatcherOptions:
              cost_thresh: 0.99
              bound_value: 1.00
            DistanceMeasurementMethod: CenterDistance
            DistanceMeasurementParams:
              max_distance: 5.0 # 前后帧最大距离(m)
              max_velocity: 50 # 障碍物最大速度(m/s)
          TrackerMethod: TailCenterTrackerCV # NearestCornerTrackerCV、TailCenterTrackerCV
          TrackerParams:
            fov_angle: 120.0
            x_offset: 7.5
            y_offset: 1.6