Type: BEVLANECONE
Config:
  Name: "CAMERA_0_F60"
  Type: "undistorted"
  ConfigFile: "/opt/trunk_vision/model/bevlaneconemodel/conf/config.toml"
  PostProcess:
    Ransac:
      MaxIterations: 5
      InlierPtsRate: 0.8
      Degree: 3
    MinConeMarginPtsThreshold: 5
    BEVLanePtMinInterval: 2.0 # bev车道线两点之间的最小间隔
    DetectedLaneMinPts: 10  # 车道线检测点数最小限制
    DetectedLaneMinLengthX: 20.0 # 车道线远端点的最小距离限制
    DetectedLaneMinRangeX: 20.0 # 车道线检测长度最短限制
    LaneBevFittingExponent: 3
