Type: FodVisionPostProcessSany
Config:
  Tracker:
    Switch: true
    TrackerPipelineMethod: SimpleTrack
    TrackerPipelineParams:
      GeneralParams:
        min_lifetime_output: 3
        max_consecutive_lost_num: 5
        min_consecutive_valid_num: 3
        max_velocity: 50.0 # 障碍物最大速度(m/s)
      IDPool:
        start_id: 1
        max_id: 255
      MatcherMethod: OneStageMatcher
      MatcherParams:
        MatcherOptions:
          cost_thresh: 0.99
          bound_value: 1.00
        DistanceMeasurementMethod: CenterDistance
        DistanceMeasurementParams:
          max_distance: 5.0 # 前后帧最大距离(m)
          max_velocity: 50 # 障碍物最大速度(m/s)
          heading_limit: true # 航向角匹配约束开关
          max_theta_diff: 0.785 # pi/4, heading角度差阈值(rad)
          max_projection_distance: 2.0 # 在heading垂直方向上的投影距离阈值(m)
      TrackerMethod: CenterTrackerCV # NearestCornerTrackerCV、TailCenterTrackerCV、CenterTrackerCV
