Type: BASE
Config:
  Name: "LIDAR_0"
  GroundDetection:
    Switch: true
    Method: JCP
    MethodParams:
      min_z: -1.0
      max_z: 3.0
      min_range: 0.0
      max_range: 130.0
      delta_R: 0.8
      horizon_fov: 130.0
      horizon_resolution: 0.2
      vertical_ring_number: 128
      threshold_height: 0.3
      threshold_slope: 10.0
      threshold_d: 2.0
      threshold_s: 5.0
      sensor_height: 3.29
      sensor_pitch: 7.45
      roi_min_y: -18.0
      roi_max_y: 18.0
      roi_x: [0.0, 20.0, 30.0, 40.0, 80.0]
      threshold_dis: 0.15
      threshold_direction: 0.96
      roi_range: 9.6