Type: BEVLanePost
Config:
  # Name: "CAMERA_0_F60"
  # 还有很多参数没有放出来，具体看bev_lane_post_impl.h
  Tracker:
    Basic:
      CameraName: "CAMERA_0_F60"
      NumAnchor: 9
      IouThres: 0.5
      MaxId: 254
      MinHits: 5
      MinWorldPtsNumThresh: 10
      MaxStartDistThresh: 40
      
    TrackletBasic:
      OccupiedGridXStart: 5
      OccupiedGridXMiddle: 15
      OccupiedGridXEnd: 80
      OccupiedXStepDense: 0.05
      OccupiedXStepSparse: 0.3
      QueueSize: 5
      FarXLimit: 120.0
      NearXLimit: -10.0
      YLimit: 20.0
      FitPtNumLimit: 5
      MaxFusionPtAge: 120000  
      # output criteria
      OutputQualityMinThresh: 0.7
      OutputMinHitsThresh: 5
      OutputMinAgeThresh: 5
      # bad tracklet standard
      MaxLostAgeThresh: 5  # 连续丢检测，删除tracklet
      MinFusionPtsNumThresh: 5  # 有效融合点太少，删除tracklet

    LaneQuality:
      CheckRangeNearX: -5.0
      CheckRangeFarX: 120
      LineOutlinerThres: 1.0
      NormMaxStdDeviation: 1.0
    
    LanePositionSelect:
      Switch: False
    
    EgoLaneHoldOnMode:
      Switch: False
