Type: BEVLanePost
Config:
  Name: "CAMERA_0_F60"
  # 还有很多参数没有放出来，具体看bev_lane_post_impl.h
  LaneQuality:
    CheckRangeNearX: -5.0
    CheckRangeFarX: 70
    LineOutlinerThres: 1.0
    NormMaxStdDeviation: 1.0