# 三一新疆项目车辆传感器配置文件
VEHICLE_NAME: "SANY_1"
Sensors:
  - Type: "LIDAR"
    Name: "LIDAR_0"
    SubTypes: ["origin", "tf", "ground", "noground"]
    BufferSize: 5
    MaxTimeDelay: 0.3
  - Type: "CAMERA"
    Name: "CAMERA_0_F60"
    SubTypes: ["origin", "undistorted"]
    BufferSize: 5
    MaxTimeDelay: 0.3
  - Type: "ODOMETRY"
    Name: "ODOMETRY"
    BufferSize: 200
    MaxTimeDelay: 0.04
  - Type: "RADAR_ARS430"
    Name: "RADAR_0"
    BufferSize: 10
    MaxTimeDelay: 0.3
  - Type: "RADAR_CRT5P"
    Name: "RADAR_1"
    BufferSize: 10
    MaxTimeDelay: 0.3
  - Type: "RADAR_CRT5P"
    Name: "RADAR_5"
    BufferSize: 10
    MaxTimeDelay: 0.3
  - Type: "RADAR_CRT5P"
    Name: "RADAR_7"
    BufferSize: 10
    MaxTimeDelay: 0.3
  - Type: "RADAR_CRT5P"
    Name: "RADAR_11"
    BufferSize: 10
    MaxTimeDelay: 0.3
