# 根目录传给app::manager
# 根目录的config键对应的嵌套值传给app::plannerbase->Init
# 由于app::plannerbase->Init函数会检查传入yaml节点的顶层有无method键，所以顶层添加了一个method键值对，但method键值对实际是在第二层config的嵌套结构中被使用的，见app::plannerbase->Init
# 第二层的config键对应的嵌套值被传入algo::plannerbase->Iint函数，正式完成算法初始化
Type: quinticpolynomial
Method: HybridAStarBridge #HybridAStar or QuinticPolynomial or HybridAStarBridge
Config:
    MaxAccel: 1.0
    MaxJerk: 0.5
    TimeStep: 0.1
    PlanningTime: 5.0
    PathResolution: 50
    step_length: 0.1
    max_segment_length_: 20.0
    off_track_threshold_: 1.0
    end_threshold_: 5  # 距离最后一个点还剩5个点 发送trajectory_state_状态
    min_speed_threshold_: 0.01  # Minimum speed threshold 计算匹配点用
    default_speed: 1.0 # default speed [m/s]
    MAX_T: 100.0 # maximum time to the goal [s]
    MIN_T: 5.0 # minimum time to the goal[s]
    max_accel: 1.0  # max accel [m/ss]
    max_jerk: 0.5  # max jerk [m/sss]
    dt: 0.1  # time tick [s]
    spacing: 0.2  # distance between points on the trajectory [m]
    output_tf_frame: 0 # 输出路径坐标系，0：world坐标系，1：base_link坐标系
    #######hybrid_a_star######
    #车参数#
    length: 2.8
    width: 1.6
    wheelbase: 2.0
    max_steering_angle: 45.0 ##角度，用浮点数表示
    v_max_vehicle: 1.0 #最大车速（算法约束）
    a_lat_max: 0.5 #最大横向加速度（转弯约束）
    a_max: 0.5 #最大加速度（加减速约束）
    #规划参数#
    segment_length: 1.6   #每次扩展的轨迹段长度（总长度）
    collision_check_step: 0.5 #碰撞检测步长(米)
    steering_angle_partitions: 10 #转向角分段数
    segment_length_discrete_num: 8 #轨迹段长度离散化数
    steering_penalty: 1.5 #转向惩罚系数（惩罚非直行）
    reversing_penalty: 3.0 #倒车惩罚系数
    steering_change_penalty: 2.0 # 转向变化惩罚系数（惩罚频繁变舵）
    shot_distance: 4.0 # 尝试RS路径（解析扩展）的距离阈值
    #测试用#
    debug: 1 #调试模式，0：关闭，1：开启
    #pgm地址#
    map_file: "/home/nvidia/tju_auto/ros/src/map/map.pgm" #绝对地址
    yaml_file: "/home/nvidia/tju_auto/ros/src/map/map.yaml" #绝对地址
    ########重规划参数#########
    tolarent_cte: 0.3 #CTE误差容忍度 米
    tolarent_heading: 0.1745 #heading误差容忍度 rad