Type: ODSparse4D
Config: 
  DistortionMap:
    MinX: -1200
    MinY: -300
    MaxX: 1600
    MaxY: 1200
  ModelConfig: /home/wangxu/Code/1_dev/A_COMMON/sparse4d/cross_modaility/sparse4d/ckpt/exps/Sany2SurOD/30_100m/v1.3_DS_v1.6_5V_30_100m/deploy/config_5v_300query.toml
  Cameras: ["CAMERA_0_F30", "CAMERA_0_F60", "CAMERA_0_F190", "CAMERA_3_F190", "CAMERA_9_F190"]
